service: facebook-integration
useDotenv: true
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-step-functions
  - serverless-plugin-aws-alerts
  - serverless-plugin-split-stacks
  - serverless-python-requirements
  - serverless-plugin-log-retention
  - serverless-plugin-tracing

custom:
  environments:
    test: 'test'
  businessImpact:
    test: 'test'
  prune:
    automatic: true
    includeLayers: true
    number: ${env:PRUNE_NUMBER}
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false 
  serviceTags:
    Managed-by: 'prueba-lambda'
    Team: 'test'
    Country: 'Colombia'
    Owner: 'Leonardo'
  dotenv:
    include: none

package:
  individually: true

provider:
  name: aws
  apiGateway:
    apiKeys:
      - name: leonardoKey
        value: leonardoValue12345678910111213141516
    usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  runtime: python3.10
  region: ${env:REGION}
  stage: ${opt:stage, 'default'}
  memorySize: 512
  timeout: ${env:TIMEOUT}
  logRetentionInDays: ${env:LOGS_RETENTION_DAYS}
  stackTags: ${self:custom.serviceTags}

resources:
  Resources:
    iamRolParaLambda: ${file(infrastructure/iam/lambda/iamRolParaLambda.yaml):iamRolParaLambda}

functions:
  lambdaAuthorizer:
    handler: src/authorizer.lambda_handler  # Asegúrate de que la ruta y la función sean correctas
    runtime: python3.10
    role: iamRolParaLambda
    events:
      - http:
          method: get
          path: /auth  # Ruta para el Lambda Authorizer

  facebook:
    handler: src/facebook_integration.gestor.lambda_handler  # Asegúrate de que la ruta y la función sean correctas
    runtime: python3.10
    role: iamRolParaLambda
    environment:
      REGION: ${env:REGION}
      LOG_LEVEL: ${env:LOG_LEVEL}
      LOG_FORMAT: ${env:LOG_FORMAT}
    events:
      - http:
          method: post
          path: /webhook
          authorizer: lambdaAuthorizer
          private: true
      - http:
          method: get
          path: /webhook
          authorizer: lambdaAuthorizer
          private: true
