  lambdaAuthorizer:
    module: src/authorizer
    handler: authorizer.lambda_handler
    runtime: python3.10
    name: lambda-authorizer
    role: iamRolAuthorizer
    events:
      - http:
          method: get
          path: /auth  # Ruta del authorizer