  facebook:
    module: src/facebook_integration
    handler: gestor.lambda_handler 
    runtime: python3.10
    name: facebook-function
    role: iamRolLambda
    environment:
      REGION: ${env:REGION}
      LOG_LEVEL: ${env:LOG_LEVEL}
      LOG_FORMAT: ${env:LOG_FORMAT}
    events:
      - http:
          method: post
          path: /webhook
          authorizer:
            name: lambdaAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: someRegex
            type: token
          private: true
      - http:
          method: get
          path: /webhook
          authorizer:
            name: lambdaAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: someRegex
            type: token
          private: true

