  Facebook:
    module: src/facebook_integration
    handler: gestor.lambda_handler
    runtime: python3.10
    name: facebook-lambda
    role: iamRolParaLambda
    environment:
      REGION: ${env:REGION}
      LOG_LEVEL: ${env:LOG_LEVEL}
      LOG_FORMAT: ${env:LOG_FORMAT}
    events:
      - http:
          method: post
          path: /webhook
          private: true
      - http:
          method: get
          path: /webhook
          private: true
      
