name: Hello World Test

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hola Mundo desde GitHub Actions 🚀"
